### ISSUE TITLE
IndexOutOfRangeException when serializing with FieldBitLengthAttribute

### ISSUE THREAD

**Issue by mixandmatch025** [jefffhaynes/BinarySerializer#107]
Hi, I'm trying to serialize the following class:
```
public class ClassToSerialize
{
   [FieldOrder(0)]
   public byte Field1 { get; set; }
   [FieldOrder(1)]
   [FieldBitLength(4)]
   public byte Field2 { get; set; }
   [FieldOrder(2)]
   [FieldBitLength(6)]
   public byte Field3 { get; set; }
   [FieldOrder(3)]
   public byte Field4 { get; set; }
   [FieldOrder(4)]
   [FieldBitLength(6)]
   public byte Field5 { get; set; }
}
```
Attempting to serialize this results in an ArgumentOutOfRangeException. Is this not expected to work?

**Comment by jefffhaynes** [comment]
No, that should work.  Can you post the full exception?  Thanks

________________________________

**Comment by mixandmatch025** [comment]
The exception is of type IndexOutOfRangeException, the full stack I get is - 

Unhandled Exception: System.InvalidOperationException: Error serializing type 'ConsoleApp1.ClassToSerialize'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing type 'ConsoleApp1.ClassToSerialize'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'Field4'.  See inner exception for detail. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BinarySerialization.BoundedStream.WriteImpl(Byte[] buffer, FieldLength length)
   at BinarySerialization.BoundedStream.WriteImpl(Byte[] buffer, FieldLength length)
   at BinarySerialization.BoundedStream.WriteImpl(Byte[] buffer, FieldLength length)
   at BinarySerialization.BoundedStream.WriteImpl(Byte[] buffer, FieldLength length)
   at BinarySerialization.AsyncBinaryWriter.Write(Byte[] data, FieldLength fieldLength)
   at BinarySerialization.Graph.ValueGraph.ValueValueNode.SerializeOverride(BoundedStream stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.SerializeInternal(BoundedStream stream, Func`1 maxLengthDelegate, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(BoundedStream stream, EventShuttle eventShuttle, Boolean align)
   --- End of inner exception stack trace ---
   at BinarySerialization.Graph.ValueGraph.ValueNode.ThrowSerializationException(Exception e)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(BoundedStream stream, EventShuttle eventShuttle, Boolean align)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.ObjectSerializeOverride(BoundedStream stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.SerializeInternal(BoundedStream stream, Func`1 maxLengthDelegate, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(BoundedStream stream, EventShuttle eventShuttle, Boolean align)
   --- End of inner exception stack trace ---
   at BinarySerialization.Graph.ValueGraph.ValueNode.ThrowSerializationException(Exception e)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(BoundedStream stream, EventShuttle eventShuttle, Boolean align)
   at BinarySerialization.Graph.ValueGraph.ValueNode.SerializeInternal(BoundedStream stream, Func`1 maxLengthDelegate, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(BoundedStream stream, EventShuttle eventShuttle, Boolean align)
   --- End of inner exception stack trace ---
   at BinarySerialization.Graph.ValueGraph.ValueNode.ThrowSerializationException(Exception e)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(BoundedStream stream, EventShuttle eventShuttle, Boolean align)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\rep1438\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 24

**Comment by jefffhaynes** [comment]
Confirmed this is a bug

**Comment by jefffhaynes** [comment]
Pushed in 8.1.2.  Thanks!

**Comment by mixandmatch025** [comment]
Thanks for the quick response!
