### ISSUE TITLE
Another Chunk Container Error... now on Serialize: Not a bindable source?

### ISSUE THREAD

**Issue by jda808** [jefffhaynes/BinarySerializer#16]
I'm coming across an issue again with nested subtypes. This time it occurs on serialization. What's baffling me is that It binds fine by itself, but when nested it doesn't work. It also doesn't work nested when I manually implement IBinarySerializable

Test Name:	DeserializeOneZoneOneSampleThenInsertAuthorChunk
Test FullName:	Pandacorn.Core.XXXX.Tests.XXXXBasicUnitTests.DeserializeOneZoneOneSampleThenInsertAuthorChunk
Test Source:	C:\X\XXXX\XXXXXX\Pandacorn.Core.Tests\XXXX\ChunkyTests.cs : line 38
Test Outcome:	Failed
Test Duration:	0:00:00.2779704

Result StackTrace:	
at BinarySerialization.Graph.Binding.GetBoundValue(ValueNode target) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\Binding.cs:line 85
   at BinarySerialization.Graph.ValueGraph.ValueNode.<Serialize>b__21_0(ConditionalBinding binding) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 106
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 105
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 112
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ValueNode.MeasureOverride() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 216
   at BinarySerialization.Graph.ValueGraph.ValueNode.<Bind>b__19_0() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 59
   at BinarySerialization.Graph.ValueGraph.ValueValueNode.get_BoundValue() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueValueNode.cs:line 45
   at BinarySerialization.Graph.ValueGraph.ValueValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueValueNode.cs:line 64
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 112
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.CollectionValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\CollectionValueNode.cs:line 27
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 112
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ValueNode.MeasureOverride() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 216
   at BinarySerialization.Graph.ValueGraph.ValueNode.<Bind>b__19_0() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 59
   at BinarySerialization.Graph.ValueGraph.ValueValueNode.get_BoundValue() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueValueNode.cs:line 45
   at BinarySerialization.Graph.ValueGraph.ValueValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueValueNode.cs:line 64
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 112
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.CollectionValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\CollectionValueNode.cs:line 27
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 112
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ValueNode.MeasureOverride() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 216
   at BinarySerialization.Graph.ValueGraph.ValueNode.<Bind>b__19_0() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 59
   at BinarySerialization.Graph.ValueGraph.ValueValueNode.get_BoundValue() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueValueNode.cs:line 45
   at BinarySerialization.Graph.ValueGraph.ValueValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueValueNode.cs:line 64
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 112
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.Graph.ValueGraph.ContextValueNode.SerializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ContextValueNode.cs:line 85
   at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 119
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 132
   at BinarySerialization.BinarySerializer.Serialize(Stream stream, Object value, Object context) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\BinarySerializer.cs:line 130
   at Pandacorn.Core.XXXX.Tests.XXXXBasicUnitTests.DeserializeOneZoneOneSampleThenInsertAuthorChunk() in C:\s\Pandacorn\XXXX\Pandacorn.Core.Tests\XXXX\ChunkyTests.cs:line 62
Result Message:	
Test method Pandacorn.Core.XXXX.Tests.XXXXBasicUnitTests.DeserializeOneZoneOneSampleThenInsertAuthorChunk threw exception: 
System.InvalidOperationException: Error serializing type 'Pandacorn.Core.NNXT.ChunkContainer'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing type 'Pandacorn.Core.XXXX.ChunkContainer'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'ChunkLength'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'Chunk'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'Chunks'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing type 'Pandacorn.Core.XXXX.ChunkContainer'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'ChunkLength'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'Chunk'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'CATS'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing type 'Pandacorn.Core.XXXX.ChunkContainer'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'ChunkLength'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'Chunk'.  See inner exception for detail. ---> System.InvalidOperationException: Error serializing member 'PhysicalSampleName'.  See inner exception for detail. ---> System.InvalidOperationException: Not a bindable source.

**Comment by jefffhaynes** [comment]
Do I have the code for this?  I don't see it in the stuff you sent me.

**Comment by jda808** [comment]
Oops no. Sending it right now.

**Comment by jefffhaynes** [comment]
Fixed in 2.4
