### ISSUE TITLE
IgnoreAttribute being .. ignored? 

### ISSUE THREAD

**Issue by Ruslebiffen** [jefffhaynes/BinarySerializer#21]
Hi, me again. 

I am having issues with the IgnoreAttribute in certain cases. I have used it elsewhere, and it works

However, in one of my classes, I get at exception when deserializing.

    System.InvalidOperationException: 'Module' does not have a FieldOrder attribute.  All serializable fields or properties in a class with more than one member must specify a FieldOrder attribute.

If I comment out these fields, the deserialization works perfectly. Nothing in the object being deserialized is called "Module", so I assume that's something in the serializer?

Here is the rest of the stack trace:

```
    at BinarySerialization.Graph.TypeGraph.ObjectTypeNode.GenerateChildrenImpl(Type parentType)
   at BinarySerialization.Graph.TypeGraph.ObjectTypeNode.Construct()
   at BinarySerialization.Graph.TypeGraph.ObjectTypeNode.GetSubType(Type type)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.set_Value(Object value)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.set_Value(Object value)
   at BinarySerialization.Graph.ValueGraph.CustomValueNode.ObjectDeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.CollectionValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.ObjectDeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.CollectionValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.ObjectDeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ContextValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle)
   at BinarySerialization.BinarySerializer.Deserialize[T](Stream stream, Object context)
   at BinarySerialization.BinarySerializer.Deserialize[T](Byte[] data, Object context)
```

**Comment by jefffhaynes** [comment]
Hm, I don't think Module comes from the framework. Any chance I can get the class definition for what you're trying to serialize?

**Comment by jefffhaynes** [comment]
Oh also there was a bug like this in a previous version of the serializer. Can you just confirm that you're updated to latest?

**Comment by Ruslebiffen** [comment]
I searched for all types in solution with "Module" in it, and it found nothing. Thought there is a type Module in `System.Reflection` that it found. Also, this class implements `IBinarySerializable` because of some "tricky" properties sharing a single byte. I'll edit the code for the class a bit and put it up here.

**Comment by jefffhaynes** [comment]
Ok I'll also give you a heads up that I'm actively working on a complex IBinarySerializable bug. It's hard to see how it might be related but who knows. I was under the impression you should only see it when also using a subtype that implements IBinarySerializable.

**Comment by Ruslebiffen** [comment]
Here is a simple class demonstrating the issue:

```
    public class FailingClass 
    {
        [FieldOrder(0)]
        public byte EncodedDataType { get; set; }

        [Ignore]
        public Type DataType
        {
            get { return DataValueType.Types[EncodedDataType]; }
        }
    }
```

**Comment by Ruslebiffen** [comment]
I got curious and poked around a bit. I did some changes in ObjectTypeNode in GenerateChildrenImpl():

```
            if (parentType.BaseType != null)
            {
                var baseChildren = GenerateChildrenImpl(parentType.BaseType);
                return baseChildren.Concat(children);
            }

            return children;
```

to

```
            if (parentType.BaseType != null)
            {
                var baseChildren = GenerateChildrenImpl(parentType.BaseType);
                return baseChildren.Concat(serializableChildren);
            }

            return serializableChildren;
``` 

The change being that it doesn't return the properties or fields that are ignored and were filtered out earlier. This broke multiple CustomTests however, but all other tests ran fine. So I guess you had done it this way for a purpose :) Impressive library you have made btw.

**Comment by jefffhaynes** [comment]
This turned out to be a pretty serious bug that could have caused problems in other places.  Essentially I wasn't passing down the attributes (like ignore) to the subtype placeholders on object types.  So good find!  

Thanks, I appreciate your feedback and taking the time to play with it.  Fixed the bug and pushed 4.4.2.  Let me know if you have any other issues with it.

**Comment by jefffhaynes** [comment]
Oops, I screwed up 4.4.2.  Grab 4.4.3.

**Comment by Ruslebiffen** [comment]
I updated to 4.4.4 and tried deserializing the class I was having issues with, and I still have the same problem.

**Comment by jefffhaynes** [comment]
That's weird. Ok, let me know how it's looking.

**Comment by jefffhaynes** [comment]
Great, thanks for the find
